// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: internal.proto

package internalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clock         map[string]int32       `protobuf:"bytes,1,rep,name=clock,proto3" json:"clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClock) GetClock() map[string]int32 {
	if x != nil {
		return x.Clock
	}
	return nil
}

type StoredValue struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Value             *structpb.Value        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	VectorClock       *VectorClock           `protobuf:"bytes,2,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
	Conflicts         []*StoredValue         `protobuf:"bytes,3,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,4,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StoredValue) Reset() {
	*x = StoredValue{}
	mi := &file_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredValue) ProtoMessage() {}

func (x *StoredValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredValue.ProtoReflect.Descriptor instead.
func (*StoredValue) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

func (x *StoredValue) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StoredValue) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

func (x *StoredValue) GetConflicts() []*StoredValue {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *StoredValue) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

type GetLocalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocalRequest) Reset() {
	*x = GetLocalRequest{}
	mi := &file_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocalRequest) ProtoMessage() {}

func (x *GetLocalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocalRequest.ProtoReflect.Descriptor instead.
func (*GetLocalRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{2}
}

func (x *GetLocalRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetLocalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         *StoredValue           `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocalResponse) Reset() {
	*x = GetLocalResponse{}
	mi := &file_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocalResponse) ProtoMessage() {}

func (x *GetLocalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocalResponse.ProtoReflect.Descriptor instead.
func (*GetLocalResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{3}
}

func (x *GetLocalResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetLocalResponse) GetValue() *StoredValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutLocalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *StoredValue           `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ForceSync     bool                   `protobuf:"varint,3,opt,name=force_sync,json=forceSync,proto3" json:"force_sync,omitempty"`
	ForceKey      bool                   `protobuf:"varint,4,opt,name=force_key,json=forceKey,proto3" json:"force_key,omitempty"`
	IsHint        bool                   `protobuf:"varint,5,opt,name=is_hint,json=isHint,proto3" json:"is_hint,omitempty"`
	OriginNode    string                 `protobuf:"bytes,6,opt,name=origin_node,json=originNode,proto3" json:"origin_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutLocalRequest) Reset() {
	*x = PutLocalRequest{}
	mi := &file_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutLocalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutLocalRequest) ProtoMessage() {}

func (x *PutLocalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutLocalRequest.ProtoReflect.Descriptor instead.
func (*PutLocalRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{4}
}

func (x *PutLocalRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutLocalRequest) GetValue() *StoredValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutLocalRequest) GetForceSync() bool {
	if x != nil {
		return x.ForceSync
	}
	return false
}

func (x *PutLocalRequest) GetForceKey() bool {
	if x != nil {
		return x.ForceKey
	}
	return false
}

func (x *PutLocalRequest) GetIsHint() bool {
	if x != nil {
		return x.IsHint
	}
	return false
}

func (x *PutLocalRequest) GetOriginNode() string {
	if x != nil {
		return x.OriginNode
	}
	return ""
}

type RepairKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *StoredValue           `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairKeyRequest) Reset() {
	*x = RepairKeyRequest{}
	mi := &file_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairKeyRequest) ProtoMessage() {}

func (x *RepairKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairKeyRequest.ProtoReflect.Descriptor instead.
func (*RepairKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{5}
}

func (x *RepairKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RepairKeyRequest) GetValue() *StoredValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type HintedWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *StoredValue           `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TargetNode    string                 `protobuf:"bytes,3,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"`
	Attempts      int32                  `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HintedWrite) Reset() {
	*x = HintedWrite{}
	mi := &file_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HintedWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HintedWrite) ProtoMessage() {}

func (x *HintedWrite) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HintedWrite.ProtoReflect.Descriptor instead.
func (*HintedWrite) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{6}
}

func (x *HintedWrite) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HintedWrite) GetValue() *StoredValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *HintedWrite) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

func (x *HintedWrite) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type StoreHintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hint          *HintedWrite           `protobuf:"bytes,1,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreHintRequest) Reset() {
	*x = StoreHintRequest{}
	mi := &file_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreHintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreHintRequest) ProtoMessage() {}

func (x *StoreHintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreHintRequest.ProtoReflect.Descriptor instead.
func (*StoreHintRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{7}
}

func (x *StoreHintRequest) GetHint() *HintedWrite {
	if x != nil {
		return x.Hint
	}
	return nil
}

type GetMerkleBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        int32                  `protobuf:"varint,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerkleBucketRequest) Reset() {
	*x = GetMerkleBucketRequest{}
	mi := &file_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerkleBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerkleBucketRequest) ProtoMessage() {}

func (x *GetMerkleBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerkleBucketRequest.ProtoReflect.Descriptor instead.
func (*GetMerkleBucketRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{8}
}

func (x *GetMerkleBucketRequest) GetBucket() int32 {
	if x != nil {
		return x.Bucket
	}
	return 0
}

type MerkleLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []string               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleLevel) Reset() {
	*x = MerkleLevel{}
	mi := &file_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleLevel) ProtoMessage() {}

func (x *MerkleLevel) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleLevel.ProtoReflect.Descriptor instead.
func (*MerkleLevel) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{9}
}

func (x *MerkleLevel) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type MerkleTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leaves        []string               `protobuf:"bytes,1,rep,name=leaves,proto3" json:"leaves,omitempty"`
	Levels        []*MerkleLevel         `protobuf:"bytes,2,rep,name=levels,proto3" json:"levels,omitempty"`
	KeyMap        map[string]string      `protobuf:"bytes,3,rep,name=key_map,json=keyMap,proto3" json:"key_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Root          string                 `protobuf:"bytes,5,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleTreeResponse) Reset() {
	*x = MerkleTreeResponse{}
	mi := &file_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleTreeResponse) ProtoMessage() {}

func (x *MerkleTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleTreeResponse.ProtoReflect.Descriptor instead.
func (*MerkleTreeResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{10}
}

func (x *MerkleTreeResponse) GetLeaves() []string {
	if x != nil {
		return x.Leaves
	}
	return nil
}

func (x *MerkleTreeResponse) GetLevels() []*MerkleLevel {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *MerkleTreeResponse) GetKeyMap() map[string]string {
	if x != nil {
		return x.KeyMap
	}
	return nil
}

func (x *MerkleTreeResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MerkleTreeResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type MemberState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Host             string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port             int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	GrpcPort         int32                  `protobuf:"varint,4,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	Heartbeat        int64                  `protobuf:"varint,5,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	LastSeenUnixNano int64                  `protobuf:"varint,7,opt,name=last_seen_unix_nano,json=lastSeenUnixNano,proto3" json:"last_seen_unix_nano,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MemberState) Reset() {
	*x = MemberState{}
	mi := &file_internal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberState) ProtoMessage() {}

func (x *MemberState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberState.ProtoReflect.Descriptor instead.
func (*MemberState) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{11}
}

func (x *MemberState) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MemberState) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *MemberState) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MemberState) GetGrpcPort() int32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *MemberState) GetHeartbeat() int64 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

func (x *MemberState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MemberState) GetLastSeenUnixNano() int64 {
	if x != nil {
		return x.LastSeenUnixNano
	}
	return 0
}

type GossipRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	NodeId        string                  `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Host          string                  `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	GrpcPort      int32                   `protobuf:"varint,4,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	Heartbeat     int64                   `protobuf:"varint,5,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Members       map[string]*MemberState `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_internal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{12}
}

func (x *GossipRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GossipRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GossipRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GossipRequest) GetGrpcPort() int32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *GossipRequest) GetHeartbeat() int64 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

func (x *GossipRequest) GetMembers() map[string]*MemberState {
	if x != nil {
		return x.Members
	}
	return nil
}

type OperationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationStatus) Reset() {
	*x = OperationStatus{}
	mi := &file_internal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStatus) ProtoMessage() {}

func (x *OperationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStatus.ProtoReflect.Descriptor instead.
func (*OperationStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{13}
}

func (x *OperationStatus) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OperationStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_proto protoreflect.FileDescriptor

const file_internal_proto_rawDesc = "" +
	"\n" +
	"\x0einternal.proto\x12\binternal\x1a\x1cgoogle/protobuf/struct.proto\"\x7f\n" +
	"\vVectorClock\x126\n" +
	"\x05clock\x18\x01 \x03(\v2 .internal.VectorClock.ClockEntryR\x05clock\x1a8\n" +
	"\n" +
	"ClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xda\x01\n" +
	"\vStoredValue\x12,\n" +
	"\x05value\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x05value\x128\n" +
	"\fvector_clock\x18\x02 \x01(\v2\x15.internal.VectorClockR\vvectorClock\x123\n" +
	"\tconflicts\x18\x03 \x03(\v2\x15.internal.StoredValueR\tconflicts\x12.\n" +
	"\x13timestamp_unix_nano\x18\x04 \x01(\x03R\x11timestampUnixNano\"#\n" +
	"\x0fGetLocalRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"U\n" +
	"\x10GetLocalResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.internal.StoredValueR\x05value\"\xc6\x01\n" +
	"\x0fPutLocalRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.internal.StoredValueR\x05value\x12\x1d\n" +
	"\n" +
	"force_sync\x18\x03 \x01(\bR\tforceSync\x12\x1b\n" +
	"\tforce_key\x18\x04 \x01(\bR\bforceKey\x12\x17\n" +
	"\ais_hint\x18\x05 \x01(\bR\x06isHint\x12\x1f\n" +
	"\vorigin_node\x18\x06 \x01(\tR\n" +
	"originNode\"Q\n" +
	"\x10RepairKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.internal.StoredValueR\x05value\"\x89\x01\n" +
	"\vHintedWrite\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.internal.StoredValueR\x05value\x12\x1f\n" +
	"\vtarget_node\x18\x03 \x01(\tR\n" +
	"targetNode\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\x05R\battempts\"=\n" +
	"\x10StoreHintRequest\x12)\n" +
	"\x04hint\x18\x01 \x01(\v2\x15.internal.HintedWriteR\x04hint\"0\n" +
	"\x16GetMerkleBucketRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\x05R\x06bucket\"%\n" +
	"\vMerkleLevel\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\tR\x06hashes\"\x87\x02\n" +
	"\x12MerkleTreeResponse\x12\x16\n" +
	"\x06leaves\x18\x01 \x03(\tR\x06leaves\x12-\n" +
	"\x06levels\x18\x02 \x03(\v2\x15.internal.MerkleLevelR\x06levels\x12A\n" +
	"\akey_map\x18\x03 \x03(\v2(.internal.MerkleTreeResponse.KeyMapEntryR\x06keyMap\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x12\n" +
	"\x04root\x18\x05 \x01(\tR\x04root\x1a9\n" +
	"\vKeyMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\vMemberState\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1b\n" +
	"\tgrpc_port\x18\x04 \x01(\x05R\bgrpcPort\x12\x1c\n" +
	"\theartbeat\x18\x05 \x01(\x03R\theartbeat\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12-\n" +
	"\x13last_seen_unix_nano\x18\a \x01(\x03R\x10lastSeenUnixNano\"\x9e\x02\n" +
	"\rGossipRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1b\n" +
	"\tgrpc_port\x18\x04 \x01(\x05R\bgrpcPort\x12\x1c\n" +
	"\theartbeat\x18\x05 \x01(\x03R\theartbeat\x12>\n" +
	"\amembers\x18\x06 \x03(\v2$.internal.GossipRequest.MembersEntryR\amembers\x1aQ\n" +
	"\fMembersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.internal.MemberStateR\x05value:\x028\x01\";\n" +
	"\x0fOperationStatus\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb7\x03\n" +
	"\x0fInternalService\x12A\n" +
	"\bGetLocal\x12\x19.internal.GetLocalRequest\x1a\x1a.internal.GetLocalResponse\x12@\n" +
	"\bPutLocal\x12\x19.internal.PutLocalRequest\x1a\x19.internal.OperationStatus\x12Q\n" +
	"\x0fGetMerkleBucket\x12 .internal.GetMerkleBucketRequest\x1a\x1c.internal.MerkleTreeResponse\x12B\n" +
	"\tRepairKey\x12\x1a.internal.RepairKeyRequest\x1a\x19.internal.OperationStatus\x12B\n" +
	"\tStoreHint\x12\x1a.internal.StoreHintRequest\x1a\x19.internal.OperationStatus\x12D\n" +
	"\x0eExchangeGossip\x12\x17.internal.GossipRequest\x1a\x19.internal.OperationStatusB\x1cZ\x1adynamo-db/proto;internalpbb\x06proto3"

var (
	file_internal_proto_rawDescOnce sync.Once
	file_internal_proto_rawDescData []byte
)

func file_internal_proto_rawDescGZIP() []byte {
	file_internal_proto_rawDescOnce.Do(func() {
		file_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)))
	})
	return file_internal_proto_rawDescData
}

var file_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_proto_goTypes = []any{
	(*VectorClock)(nil),            // 0: internal.VectorClock
	(*StoredValue)(nil),            // 1: internal.StoredValue
	(*GetLocalRequest)(nil),        // 2: internal.GetLocalRequest
	(*GetLocalResponse)(nil),       // 3: internal.GetLocalResponse
	(*PutLocalRequest)(nil),        // 4: internal.PutLocalRequest
	(*RepairKeyRequest)(nil),       // 5: internal.RepairKeyRequest
	(*HintedWrite)(nil),            // 6: internal.HintedWrite
	(*StoreHintRequest)(nil),       // 7: internal.StoreHintRequest
	(*GetMerkleBucketRequest)(nil), // 8: internal.GetMerkleBucketRequest
	(*MerkleLevel)(nil),            // 9: internal.MerkleLevel
	(*MerkleTreeResponse)(nil),     // 10: internal.MerkleTreeResponse
	(*MemberState)(nil),            // 11: internal.MemberState
	(*GossipRequest)(nil),          // 12: internal.GossipRequest
	(*OperationStatus)(nil),        // 13: internal.OperationStatus
	nil,                            // 14: internal.VectorClock.ClockEntry
	nil,                            // 15: internal.MerkleTreeResponse.KeyMapEntry
	nil,                            // 16: internal.GossipRequest.MembersEntry
	(*structpb.Value)(nil),         // 17: google.protobuf.Value
}
var file_internal_proto_depIdxs = []int32{
	14, // 0: internal.VectorClock.clock:type_name -> internal.VectorClock.ClockEntry
	17, // 1: internal.StoredValue.value:type_name -> google.protobuf.Value
	0,  // 2: internal.StoredValue.vector_clock:type_name -> internal.VectorClock
	1,  // 3: internal.StoredValue.conflicts:type_name -> internal.StoredValue
	1,  // 4: internal.GetLocalResponse.value:type_name -> internal.StoredValue
	1,  // 5: internal.PutLocalRequest.value:type_name -> internal.StoredValue
	1,  // 6: internal.RepairKeyRequest.value:type_name -> internal.StoredValue
	1,  // 7: internal.HintedWrite.value:type_name -> internal.StoredValue
	6,  // 8: internal.StoreHintRequest.hint:type_name -> internal.HintedWrite
	9,  // 9: internal.MerkleTreeResponse.levels:type_name -> internal.MerkleLevel
	15, // 10: internal.MerkleTreeResponse.key_map:type_name -> internal.MerkleTreeResponse.KeyMapEntry
	16, // 11: internal.GossipRequest.members:type_name -> internal.GossipRequest.MembersEntry
	11, // 12: internal.GossipRequest.MembersEntry.value:type_name -> internal.MemberState
	2,  // 13: internal.InternalService.GetLocal:input_type -> internal.GetLocalRequest
	4,  // 14: internal.InternalService.PutLocal:input_type -> internal.PutLocalRequest
	8,  // 15: internal.InternalService.GetMerkleBucket:input_type -> internal.GetMerkleBucketRequest
	5,  // 16: internal.InternalService.RepairKey:input_type -> internal.RepairKeyRequest
	7,  // 17: internal.InternalService.StoreHint:input_type -> internal.StoreHintRequest
	12, // 18: internal.InternalService.ExchangeGossip:input_type -> internal.GossipRequest
	3,  // 19: internal.InternalService.GetLocal:output_type -> internal.GetLocalResponse
	13, // 20: internal.InternalService.PutLocal:output_type -> internal.OperationStatus
	10, // 21: internal.InternalService.GetMerkleBucket:output_type -> internal.MerkleTreeResponse
	13, // 22: internal.InternalService.RepairKey:output_type -> internal.OperationStatus
	13, // 23: internal.InternalService.StoreHint:output_type -> internal.OperationStatus
	13, // 24: internal.InternalService.ExchangeGossip:output_type -> internal.OperationStatus
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_proto_init() }
func file_internal_proto_init() {
	if File_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_goTypes,
		DependencyIndexes: file_internal_proto_depIdxs,
		MessageInfos:      file_internal_proto_msgTypes,
	}.Build()
	File_internal_proto = out.File
	file_internal_proto_goTypes = nil
	file_internal_proto_depIdxs = nil
}
