// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: internal.proto

package internalpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalService_GetLocal_FullMethodName        = "/internal.InternalService/GetLocal"
	InternalService_PutLocal_FullMethodName        = "/internal.InternalService/PutLocal"
	InternalService_GetMerkleBucket_FullMethodName = "/internal.InternalService/GetMerkleBucket"
	InternalService_RepairKey_FullMethodName       = "/internal.InternalService/RepairKey"
	InternalService_StoreHint_FullMethodName       = "/internal.InternalService/StoreHint"
	InternalService_ExchangeGossip_FullMethodName  = "/internal.InternalService/ExchangeGossip"
)

// InternalServiceClient is the client API for InternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalServiceClient interface {
	GetLocal(ctx context.Context, in *GetLocalRequest, opts ...grpc.CallOption) (*GetLocalResponse, error)
	PutLocal(ctx context.Context, in *PutLocalRequest, opts ...grpc.CallOption) (*OperationStatus, error)
	GetMerkleBucket(ctx context.Context, in *GetMerkleBucketRequest, opts ...grpc.CallOption) (*MerkleTreeResponse, error)
	RepairKey(ctx context.Context, in *RepairKeyRequest, opts ...grpc.CallOption) (*OperationStatus, error)
	StoreHint(ctx context.Context, in *StoreHintRequest, opts ...grpc.CallOption) (*OperationStatus, error)
	ExchangeGossip(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*OperationStatus, error)
}

type internalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalServiceClient(cc grpc.ClientConnInterface) InternalServiceClient {
	return &internalServiceClient{cc}
}

func (c *internalServiceClient) GetLocal(ctx context.Context, in *GetLocalRequest, opts ...grpc.CallOption) (*GetLocalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLocalResponse)
	err := c.cc.Invoke(ctx, InternalService_GetLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) PutLocal(ctx context.Context, in *PutLocalRequest, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, InternalService_PutLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetMerkleBucket(ctx context.Context, in *GetMerkleBucketRequest, opts ...grpc.CallOption) (*MerkleTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerkleTreeResponse)
	err := c.cc.Invoke(ctx, InternalService_GetMerkleBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) RepairKey(ctx context.Context, in *RepairKeyRequest, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, InternalService_RepairKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) StoreHint(ctx context.Context, in *StoreHintRequest, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, InternalService_StoreHint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) ExchangeGossip(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, InternalService_ExchangeGossip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServiceServer is the server API for InternalService service.
// All implementations must embed UnimplementedInternalServiceServer
// for forward compatibility.
type InternalServiceServer interface {
	GetLocal(context.Context, *GetLocalRequest) (*GetLocalResponse, error)
	PutLocal(context.Context, *PutLocalRequest) (*OperationStatus, error)
	GetMerkleBucket(context.Context, *GetMerkleBucketRequest) (*MerkleTreeResponse, error)
	RepairKey(context.Context, *RepairKeyRequest) (*OperationStatus, error)
	StoreHint(context.Context, *StoreHintRequest) (*OperationStatus, error)
	ExchangeGossip(context.Context, *GossipRequest) (*OperationStatus, error)
	mustEmbedUnimplementedInternalServiceServer()
}

// UnimplementedInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalServiceServer struct{}

func (UnimplementedInternalServiceServer) GetLocal(context.Context, *GetLocalRequest) (*GetLocalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocal not implemented")
}
func (UnimplementedInternalServiceServer) PutLocal(context.Context, *PutLocalRequest) (*OperationStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutLocal not implemented")
}
func (UnimplementedInternalServiceServer) GetMerkleBucket(context.Context, *GetMerkleBucketRequest) (*MerkleTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerkleBucket not implemented")
}
func (UnimplementedInternalServiceServer) RepairKey(context.Context, *RepairKeyRequest) (*OperationStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RepairKey not implemented")
}
func (UnimplementedInternalServiceServer) StoreHint(context.Context, *StoreHintRequest) (*OperationStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreHint not implemented")
}
func (UnimplementedInternalServiceServer) ExchangeGossip(context.Context, *GossipRequest) (*OperationStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeGossip not implemented")
}
func (UnimplementedInternalServiceServer) mustEmbedUnimplementedInternalServiceServer() {}
func (UnimplementedInternalServiceServer) testEmbeddedByValue()                         {}

// UnsafeInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalServiceServer will
// result in compilation errors.
type UnsafeInternalServiceServer interface {
	mustEmbedUnimplementedInternalServiceServer()
}

func RegisterInternalServiceServer(s grpc.ServiceRegistrar, srv InternalServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalService_ServiceDesc, srv)
}

func _InternalService_GetLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_GetLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetLocal(ctx, req.(*GetLocalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_PutLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutLocalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).PutLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_PutLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).PutLocal(ctx, req.(*PutLocalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetMerkleBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerkleBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetMerkleBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_GetMerkleBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetMerkleBucket(ctx, req.(*GetMerkleBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_RepairKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepairKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).RepairKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_RepairKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).RepairKey(ctx, req.(*RepairKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_StoreHint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreHintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).StoreHint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_StoreHint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).StoreHint(ctx, req.(*StoreHintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_ExchangeGossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).ExchangeGossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_ExchangeGossip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).ExchangeGossip(ctx, req.(*GossipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalService_ServiceDesc is the grpc.ServiceDesc for InternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internal.InternalService",
	HandlerType: (*InternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLocal",
			Handler:    _InternalService_GetLocal_Handler,
		},
		{
			MethodName: "PutLocal",
			Handler:    _InternalService_PutLocal_Handler,
		},
		{
			MethodName: "GetMerkleBucket",
			Handler:    _InternalService_GetMerkleBucket_Handler,
		},
		{
			MethodName: "RepairKey",
			Handler:    _InternalService_RepairKey_Handler,
		},
		{
			MethodName: "StoreHint",
			Handler:    _InternalService_StoreHint_Handler,
		},
		{
			MethodName: "ExchangeGossip",
			Handler:    _InternalService_ExchangeGossip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal.proto",
}
